import{a as h,S as g,i as n}from"./assets/vendor-BAQQTdrx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const b="55695918-3f0edaddc3daf06a90200e5d1",L="https://pixabay.com/api/";async function w(e,r=1){return(await h.get(L,{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:100}})).data}const v=new g(".gallery a",{captionsData:"alt",captionDelay:250}),u=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more-btn");function S(e){const r=e.map(s=>`
      <li class="gallery-item">
        <a href="${s.largeImageURL}">
          <img src="${s.webformatURL}" alt="${s.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${s.likes}</p>
          <p><b>Views</b> ${s.views}</p>
          <p><b>Comments</b> ${s.comments}</p>
          <p><b>Downloads</b> ${s.downloads}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",r),v.refresh()}function q(){u.innerHTML=""}function M(){f.classList.add("is-visible")}function P(){f.classList.remove("is-visible")}function B(){m.classList.remove("is-hidden")}function a(){m.classList.add("is-hidden")}let l="",i=1;const E=100,p=document.querySelector(".search-form"),$=document.querySelector(".load-more-btn");p.addEventListener("submit",O);$.addEventListener("click",x);async function O(e){if(e.preventDefault(),l=e.currentTarget.elements["search-text"].value.trim(),!l){n.warning({message:"Please enter a search query"});return}i=1,q(),a(),await y(),p.reset()}async function x(){i+=1,a(),await y(),A()}async function y(){M();try{const e=await w(l,i);if(e.hits.length===0){a(),n.error({message:"Sorry, no images found. Try again!"});return}S(e.hits);const r=Math.ceil(e.totalHits/E);i>=r?(a(),n.info({message:"We're sorry, but you've reached the end of search results."})):B()}catch{n.error({message:"Error fetching images!"}),a()}finally{P()}}function A(){const e=document.querySelector(".gallery-item");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
